import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KTD 01 👻",
  description: "Generated by create next app",
};

//layout.tsx의 파일명, 컴포넌트명(RootLayout), 상위폴더 명, 파일 위치 절대 바꾸면 안됨.
// 이 파일이 시작점이기 때문임.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        

        <div className="w-full xl:w-8/10 h-screen mx-auto flex flex-col">
        <Nav />


        <main className="w-full flex flex-grow flex-col justify-start items-center overflow-y-auto">
            {children}

        </main>

        <footer className="w-full min-h-20 bg-gray-200 px-10 inline-flex justify-between items-center">
          <h3 className="m-10 flex justify-start">[K-Digital 부산대 25-1회차] AI 데이터 분석 풀스택 웹 개발자 양성과정</h3>
          <h4 className="m-5 inline-flex justify-between"> ☎️ 051-512-0311  | ✉️ www.pusan.ac.kr </h4>
        </footer>

      </div>
      </body>
    </html>
  );
}
