import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KTD 01 👻",
  description: "Generated by create next app",
};

// react의 App.txs 파일과 같은 역할
//layout.tsx의 파일명, 컴포넌트명(RootLayout), 상위폴더 명, 파일 위치 절대 바꾸면 안됨.
// 이 파일이 시작점이기 때문임.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        

        <div className="w-full xl:w-8/10 h-screen mx-auto flex flex-col">
        <Nav />


        <main className="w-full flex flex-grow flex-col justify-start items-center overflow-y-auto">
            {/* page 파일들이 children 위치에 오게 됨 */}
            {children}

        </main>

        
        <Footer />
      </div>
      </body>
    </html>
  );
}
